### ISSUE TITLE
ERROR: No matching distribution found for pywin32 (from msgtopdf) invUbuntu 20.04 LTS

### ISSUE THREAD

**Issue by Devadath** [ushills/msgtopdf#5]
Hi I tried to install msgtopdf in Ubuntu 20.04. I am getting th below given error for pywin32.
.$ sudo pip3 install msgtopdf
Collecting msgtopdf
  Using cached msgtopdf-0.1.6-py3-none-any.whl (6.2 kB)
ERROR: Could not find a version that satisfies the requirement pywin32 (from msgtopdf) (from versions: none)
ERROR: No matching distribution found for pywin32 (from msgtopdf)

Thanks
Devadath

**Comment by ushills** [comment]
Hi, the application is Windows only, although it will work on Ubuntu with Windows running as a VM.  The application uses pywin32 which is a Windows only library to access Windows APIs connecting in this case to Outlook for msg extraction.  I would love to write a open OS application to achieve the same thing as I am generally linux only but the API for Outlook is not very accessible until we all move to Office 365.  Msgtopdf has been tested on outlook msg formats back to 2011.
